### PR TITLE
Work around poor GHC performance on Diff and Merge

### PR DESCRIPTION
**Pull request by ak3n**
The problem is the same as in #71.

I also have tried to fix `Inject` and `LacksR` but haven't found tests cases with bad performance.

### CODE REVIEW

**Review by dwincort — APPROVED** [review]
I'm really sorry this took a month for me to get to, but thank you for contributing!  If `Injet` and `LacksR` aren't a problem (yet), then let's just not deal with them -- we can always modify them in the future if/when the need arises.

**Comment by ak3n** [comment]
No problem! Thanks!

**Comment by shinzui** [comment]
Is it possible to publish please?

**Comment by dwincort** [comment]
@ak3n, Wow, I totally lost track of time this summer.  Thanks for the reminder @shinzui -- I just pushed the release to hackage (https://hackage.haskell.org/package/row-types-1.0.1.1).

**Pull request merged**
